from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('specialities/', views.specialities, name='specialities'),
    path('signup/', views.signup, name='signup'),
    path('contactus/', views.contactus, name='contactus'),
    path('signin/', views.signin, name='signin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('myappointment/', views.myappointment, name='myappointment'),
    path('scheduledetails/', views.scheduledetails, name='scheduledetails'),
    path('scheduledatetime/', views.scheduledatetime, name='scheduledatetime'),
    path('scheduledoctor/', views.scheduledoctor, name='scheduledoctor'),
    path('bookappointment/', views.bookappointment, name='bookappointment'),
    path('bookappointment_done/<str:paid>', views.bookappointment_done, name='bookappointment_done'),
    path('bookappointment_pay/<str:paid>', views.bookappointment_pay, name='bookappointment_pay'),
    path('deleteuser/<int:uid>', views.deleteuser, name='deleteuser'),
    path('logout/', views.logout, name='logout'),
    path("handlerequest/", views.handlerequest, name="HandleRequest"), 
    path('updateuser/<int:uid>', views.updateuser, name='updateuser'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]
